import { UserRole } from '@/types/roles';

export interface RoleTab {
  key: string;
  label: string;
  path: string;
}

export const ROLE_TABS: Record<UserRole, RoleTab[]> = {
  admin: [
    { key: 'dashboard', label: 'Dashboard', path: '/admin' },
    { key: 'staff', label: 'Staff', path: '/admin/staff' },
    { key: 'departments', label: 'Departments', path: '/admin/departments' },
    { key: 'finance', label: 'Finance', path: '/admin/finance' },
    { key: 'expenses', label: 'Expenses', path: '/admin/expenses' },
    { key: 'approvals', label: 'Approvals', path: '/admin/approvals' },
    { key: 'claims', label: 'Claims', path: '/admin/claims' },
    { key: 'mrd', label: 'MRD', path: '/admin/mrd' },
    { key: 'mis', label: 'MIS Reports', path: '/admin/mis' },
    { key: 'audit', label: 'Audit', path: '/admin/audit' },
    { key: 'settings', label: 'Settings', path: '/admin/settings' },
  ],
  doctor: [
    { key: 'dashboard', label: 'Dashboard', path: '/doctor' },
    { key: 'patients', label: 'Patients', path: '/doctor/patients' },
    { key: 'queue', label: 'OPD Queue', path: '/doctor/queue' },
    { key: 'schedule', label: 'Schedule', path: '/doctor/schedule' },
    { key: 'labs', label: 'Labs', path: '/doctor/labs' },
    { key: 'radiology', label: 'Radiology', path: '/doctor/radiology' },
    { key: 'ipd', label: 'IPD', path: '/doctor/ipd' },
    { key: 'analytics', label: 'Analytics', path: '/doctor/analytics' },
  ],
  nurse: [
    { key: 'dashboard', label: 'Dashboard', path: '/nurse' },
    { key: 'ward', label: 'My Ward', path: '/nurse/ward' },
    { key: 'admissions', label: 'Admissions', path: '/nurse/admissions' },
    { key: 'tasks', label: 'Tasks', path: '/nurse/tasks' },
    { key: 'medications', label: 'Medications', path: '/nurse/medications' },
    { key: 'vitals', label: 'Vitals', path: '/nurse/vitals' },
    { key: 'discharge', label: 'Discharge', path: '/nurse/discharge' },
    { key: 'reports', label: 'Reports', path: '/nurse/reports' },
  ],
  receptionist: [
    { key: 'dashboard', label: 'Dashboard', path: '/reception' },
    { key: 'registration', label: 'Registration', path: '/reception/registration' },
    { key: 'appointments', label: 'Appointments', path: '/reception/appointments' },
    { key: 'checkin', label: 'Check-In', path: '/reception/checkin' },
    { key: 'queue', label: 'Queue', path: '/reception/queue' },
    { key: 'billing', label: 'Billing', path: '/reception/billing' },
    { key: 'beds', label: 'Beds', path: '/reception/beds' },
    { key: 'ipd', label: 'IPD', path: '/reception/ipd' },
  ],
  lab_technician: [
    { key: 'dashboard', label: 'Dashboard', path: '/lab' },
    { key: 'worklist', label: 'Worklist', path: '/lab/worklist' },
    { key: 'samples', label: 'Samples', path: '/lab/samples' },
    { key: 'entry', label: 'Test Entry', path: '/lab/entry' },
    { key: 'verification', label: 'Verification', path: '/lab/verification' },
    { key: 'reports', label: 'Reports', path: '/lab/reports' },
  ],
  pharmacist: [
    { key: 'dashboard', label: 'Dashboard', path: '/pharmacy' },
    { key: 'prescriptions', label: 'Prescriptions', path: '/pharmacy/prescriptions' },
    { key: 'inventory', label: 'Inventory', path: '/pharmacy/inventory' },
    { key: 'drugs', label: 'Drugs', path: '/pharmacy/drugs' },
    { key: 'billing', label: 'Billing', path: '/pharmacy/billing' },
    { key: 'suppliers', label: 'Suppliers', path: '/pharmacy/suppliers' },
    { key: 'purchase', label: 'Purchase Orders', path: '/pharmacy/purchase' },
    { key: 'queries', label: 'Queries', path: '/pharmacy/queries' },
  ],
  billing: [
    { key: 'dashboard', label: 'Dashboard', path: '/billing-dept' },
    { key: 'invoices', label: 'Invoices', path: '/billing-dept/invoices' },
    { key: 'payments', label: 'Payments', path: '/billing-dept/payments' },
    { key: 'ipd-billing', label: 'IPD Billing', path: '/billing-dept/ipd-billing' },
    { key: 'packages', label: 'Packages', path: '/billing-dept/packages' },
    { key: 'revenue', label: 'Revenue', path: '/billing-dept/revenue' },
    { key: 'insurance', label: 'Insurance', path: '/billing-dept/insurance' },
    { key: 'finance', label: 'Finance', path: '/billing-dept/finance' },
    { key: 'reports', label: 'Reports', path: '/billing-dept/reports' },
  ],
  radiologist: [
    { key: 'dashboard', label: 'Dashboard', path: '/radiology' },
    { key: 'orders', label: 'Orders', path: '/radiology/orders' },
    { key: 'worklist', label: 'Worklist', path: '/radiology/worklist' },
    { key: 'reports', label: 'Reports', path: '/radiology/reports' },
    { key: 'settings', label: 'Settings', path: '/radiology/settings' },
  ],
  ot_coordinator: [
    { key: 'dashboard', label: 'Dashboard', path: '/ot' },
    { key: 'schedule', label: 'Schedule', path: '/ot/schedule' },
    { key: 'rooms', label: 'OT Rooms', path: '/ot/rooms' },
    { key: 'teams', label: 'Teams', path: '/ot/teams' },
    { key: 'preop', label: 'Pre-Op', path: '/ot/preop' },
    { key: 'intraop', label: 'Intraoperative', path: '/ot/intraop' },
    { key: 'postop', label: 'Post-Op', path: '/ot/postop' },
    { key: 'inventory', label: 'Inventory', path: '/ot/inventory' },
    { key: 'reports', label: 'Reports', path: '/ot/reports' },
    { key: 'analytics', label: 'Analytics', path: '/ot/analytics' },
  ],
  inventory_manager: [
    { key: 'dashboard', label: 'Dashboard', path: '/inventory' },
    { key: 'catalog', label: 'Catalog', path: '/inventory/catalog' },
    { key: 'stock-entry', label: 'Stock Entry', path: '/inventory/stock-entry' },
    { key: 'distribution', label: 'Distribution', path: '/inventory/distribution' },
    { key: 'requisitions', label: 'Requisitions', path: '/inventory/requisitions' },
    { key: 'procurement', label: 'Procurement', path: '/inventory/procurement' },
    { key: 'adjustments', label: 'Adjustments', path: '/inventory/adjustments' },
    { key: 'equipment', label: 'Equipment', path: '/inventory/equipment' },
    { key: 'reports', label: 'Reports', path: '/inventory/reports' },
  ],
  emergency: [
    { key: 'dashboard', label: 'Dashboard', path: '/emergency' },
    { key: 'triage', label: 'Triage', path: '/emergency/triage' },
    { key: 'cases', label: 'Cases', path: '/emergency/cases' },
    { key: 'treatment', label: 'Treatment', path: '/emergency/treatment' },
    { key: 'orders', label: 'Orders', path: '/emergency/orders' },
    { key: 'observation', label: 'Observation', path: '/emergency/observation' },
    { key: 'mlc', label: 'MLC', path: '/emergency/mlc' },
    { key: 'ambulance', label: 'Ambulance', path: '/emergency/ambulance' },
    { key: 'reports', label: 'Reports', path: '/emergency/reports' },
  ],
  hr_manager: [
    { key: 'dashboard', label: 'Dashboard', path: '/hr' },
    { key: 'staff', label: 'Staff Profiles', path: '/hr/staff' },
    { key: 'scheduling', label: 'Scheduling', path: '/hr/scheduling' },
    { key: 'attendance', label: 'Attendance', path: '/hr/attendance' },
    { key: 'leave', label: 'Leave', path: '/hr/leave' },
    { key: 'credentials', label: 'Credentials', path: '/hr/credentials' },
    { key: 'training', label: 'Training', path: '/hr/training' },
    { key: 'performance', label: 'Performance', path: '/hr/performance' },
    { key: 'reports', label: 'Reports', path: '/hr/reports' },
  ],
};

export const ROLE_BASE_PATH: Record<UserRole, string> = {
  admin: '/admin',
  doctor: '/doctor',
  nurse: '/nurse',
  receptionist: '/reception',
  lab_technician: '/lab',
  pharmacist: '/pharmacy',
  billing: '/billing-dept',
  radiologist: '/radiology',
  ot_coordinator: '/ot',
  inventory_manager: '/inventory',
  emergency: '/emergency',
};
